config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('/surveys')

  resources :surveys do
    resources :survey_questions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :survey_questions, dependent: :destroy

    validates_uniqueness_of :name
    validates_presence_of :name
    validates :name, length: { in: 3..25 }
end

app/models/survey_question.rb
class SurveyQuestion < ApplicationRecord
    belongs_to :survey

    validates_uniqueness_of :question_text
    validates_presence_of :question_text
    validates :name, length: { in: 5..240 }
    validates_associated :survey
end

app/models/survey_questions.rb
class SurveyQuestion < ApplicationRecord
    belongs_to :survey

    validates_uniqueness :question_text
    validates_presence_of :question_text
    validates :name, length: { in: 5..240 }
    validates_associated :survey
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController
  before_action :set_survey_question

  def index
    @survey_questions = SurveyQuestion.where(survery_id: parmas[:survey_id])
  end

  def new; end

  def create
    @survey_question = SurveyQuestion.new(survey_question_params)
    if @survey_question.save
      redirect_to @survey
    else
      render :new
    end
  end

  def edit; end
  end

  def update
    if @survey_question.update(survey_question_params)
      redirect_to @review
    else
      render :edit
  end

  private

  def set_survey
    @survey = Survey.find(params[:survey_id])
  end

  def set_survey_question
    @survey_question = SurveyQuestion.find(params[:id])

  def survey_question_params
    params.require(:survey_question).permit!
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey

  def index
    @surveys = Survey.order(:name)
  end

  def new
    @survey = Survey.new
    @survey.survey_questions.build
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to surveys
    else
      render :new
    end
  end

  def edit; end

  def update
    if @survey.update(survey_params)
      redirect_to @survey
    else
      render :edit
    end
  end

  private

  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/survey_questions_helper.rb
module SurveyQuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo right">Survey Project</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to('Surveys', surveys_path) %></li>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

app/views/survey_questions/edit.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>Edit Survey Question</h4>

  </div>
</div>

app/views/survey_questions/index.html.erb
<div class="row">
  <div class="col s12 m6">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Survey Questions</h4></li>
      <!-- list survey questions for this survey -->
      <li class="collection-item">Survey Question 1</li>
    </ul>

    <div class="row">
      <div class="col s12 m6">
        <%# <%= link_to('Create Question',
                    new_survey_survey_question_path(),
                    class: "btn waves-effect waves-light") %> %>
      </div>
    </div>
  </div>
</div>

app/views/survey_questions/new.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>New Survey Question</h4>

  </div>
</div>

app/views/surveys/edit.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>Edit Survey</h4>

  </div>
</div>

app/views/surveys/index.html.erb
<div class="row">
  <div class="col s12 m6">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Surveys</h4></li>
      <!-- list surveys -->
      <li class="collection-item">Survey 1</li>
    </ul>

    <div class="row">
      <div class="col s12 m6">
        <%= link_to('Create Survey',
                    new_survey_path,
                    class: "btn waves-effect waves-light") %>
      </div>
    </div>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="row">
  <div class="col s12 m6">
    <h4>New Survey</h4>

  </div>
</div>